from shared.domain_exception import DomainException


class DomainEntityException(DomainException):
    pass
