from shared.basic_exception import CustomException


class DomainException(CustomException):
    pass
